### PR TITLE
Allow symfony 5

### PR DESCRIPTION
**Pull request by priyank989**
Allow laravel 7

### CODE REVIEW

**Comment by priyank989** [comment]
ping @antonioribeiro

**Comment by priyank989** [comment]
ping @antonioribeiro

**Comment by ruudk** [comment]
Handled in https://github.com/antonioribeiro/ia-collection/commit/97a00312ffc190cfcac3ae919ed2e122deb685f5, please clode

**Comment by priyank989** [comment]
@antonioribeiro can you please update this package pragmarx/countries as well

**Pull request closed without merging**
